### ISSUE TITLE
Move socket constants to a separate file

### ISSUE THREAD

**Issue by Nitive** [shri-2015-org/shrimp#84]
We need move socket constants to a separate file. Then if we make a mistake in event name, we get an error.

**Comment by SeqviriouM** [comment]
As I understand right, you want to put socket action's type in separate file?

**Comment by Nitive** [comment]
I want to move **constants** to separate file
```
const ADD_CHANNEL = 'ADD_CHANNEL';
const ADD_MESSAGE = 'ADD_MESSAGE';
...
```
And use constants instead strings

**Comment by Nitive** [comment]
And we can import this file on server and on client side.
