### ISSUE TITLE
Separate "server to client" and "client to server" events

### ISSUE THREAD

**Issue by Nitive** [shri-2015-org/shrimp#85]
Maybe use prefix or something like that.
We use NEW_MESSAGE as "client to server" and ADD_MESSAGE as "server to client" now

**Comment by Nitive** [comment]
I suggest using `SC_` or `CS_` prefix in every event name

**Comment by SeqviriouM** [comment]
Then we need to change action type, because we have middleware, that call socket emit depending on action's type
