### ISSUE TITLE
Draw Log In page

### ISSUE THREAD

**Issue by Nitive** [shri-2015-org/shrimp#94]

**Comment by Nitive** [comment]
![shri login](https://cloud.githubusercontent.com/assets/6770225/10119954/e9023d14-64ae-11e5-92c8-f3a58081af8a.png)
[shrimp login page.pdf](https://github.com/shri-2015-org/shrimp/files/3036/shrimp.login.page.pdf)

**Comment by dimaip** [comment]
There's a typo in Messenger. Maybe write Shrimp there?

**Comment by Nitive** [comment]
Yes, it's place for product name. I think we need another name for release.

**Comment by dimaip** [comment]
I don't mind.
